services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  Evoweb\Extender\:
    resource: '../Classes/*'

  extender.cache:
    class: TYPO3\CMS\Core\Cache\Frontend\PhpFrontend
    factory: ['Evoweb\Extender\Factory\CacheFactory', 'createCache']
    arguments: ['extender']

  Evoweb\Extender\Command\ExtenderRebuildCommand:
    arguments: ['@Evoweb\Extender\Utility\ClassCacheManager']
    tags:
      - { name: 'console.command', command: 'extender:rebuild', schedulable: false }

  Evoweb\Extender\Utility\ClassCacheManager:
    arguments:
      $classCache: '@extender.cache'
      $composerClassLoader: '@Composer\Autoload\ClassLoader'
    public: true

  Evoweb\Extender\Utility\ClassLoader:
    arguments:
      $classCache: '@extender.cache'
      $classCacheManager: '@Evoweb\Extender\Utility\ClassCacheManager'
    public: true

  Evoweb\Extender\EventListener\RegisterAutoloader:
    arguments: ['@Evoweb\Extender\Utility\ClassLoader']
    tags:
      - name: event.listener
        identifier: 'extender_extlocalconf_registerautoloader'
        method: 'onClassLoaderEvent'
        event: Evoweb\Extender\Utility\Event\ClassLoaderEvent