services:
  _defaults:
    autowire: false
    autoconfigure: false
    public: false

  Evoweb\Extender\:
    resource: '../Classes/*'

  extender.cache:
    class: TYPO3\CMS\Core\Cache\Frontend\PhpFrontend
    # We can not use CacheManager, as it can not be
    # injected/instantiated during ext_localconf.php loading
    # factory: ['@TYPO3\CMS\Core\Cache\CacheManager', 'getCache']
    # therefore we use the static Bootstrap::createCache factory instead.
    factory: ['TYPO3\CMS\Core\Core\Bootstrap', 'createCache']
    arguments: ['extender']

  Evoweb\Extender\Command\ExtenderRebuildCommand:
    arguments: ['@Evoweb\Extender\Utility\ClassCacheManager']
    tags:
      - { name: 'console.command', command: 'extender:rebuild', schedulable: false }

  Evoweb\Extender\Utility\ClassCacheManager:
    arguments:
      $classCache: '@extender.cache'
      $composerClassLoader: '@Composer\Autoload\ClassLoader'
    public: true

  Evoweb\Extender\Utility\ClassLoader:
    arguments:
      $classCache: '@extender.cache'
      $classCacheManager: '@Evoweb\Extender\Utility\ClassCacheManager'
    public: true
