services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Evoweb\Extender\:
    resource: '../Classes/*'

  cache.extender:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    # We can not use CacheManager, as it can not be
    # injected/instantiated prior (or during) ext_localconf.php
    # loading therefore we use an own factory instead.
    factory: ['@Evoweb\Extender\Cache\CacheManager', 'createCache']
    arguments: ['extender']

  Evoweb\Extender\Cache\ClassCacheManager:
    arguments:
      $classCache: '@cache.extender'
      $composerClassLoader: '@Composer\Autoload\ClassLoader'
      $classParser: '@Evoweb\Extender\Parser\ClassParser'
      $classComposer: '@Evoweb\Extender\Composer\ClassComposer'
      $register: '@Evoweb\Extender\Configuration\Register'
    public: true

  Evoweb\Extender\Command\ClearCommand:
    tags:
      -
        name: 'console.command'
        command: 'extender:rebuild'
        description: 'CLI command for the "extender" extension - clear cache'
        schedulable: false

  Evoweb\Extender\Composer\ClassComposer:
    public: true

  Evoweb\Extender\Configuration\Register:
    public: true

  Evoweb\Extender\Hooks\DataHandlerClearCachePostProcHook:
    public: true

  Evoweb\Extender\Loader\ClassLoader:
    arguments:
      $classCache: '@cache.extender'
      $classCacheManager: '@Evoweb\Extender\Cache\ClassCacheManager'
      $register: '@Evoweb\Extender\Configuration\Register'
    public: true

  Evoweb\Extender\Parser\ClassParser:
    arguments:
      $parserFactory: '@PhpParser\ParserFactory'
    public: true

  PhpParser\ParserFactory:
    public: true
