services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Evoweb\Extender\:
    resource: '../Classes/'

  cache.extender:
    class: TYPO3\CMS\Core\Cache\Frontend\FrontendInterface
    # We can't use CacheManager, as it can't be
    # injected/instantiated prior (or during) ext_localconf.php loading.
    # In consequence, we need to use our own factory instead.
    factory: [ '@Evoweb\Extender\Cache\CacheFactory', 'getCache' ]
    arguments: [ 'extender' ]

  PhpParser\ParserFactory:
    public: true
